Global Enum _
    $eBackground, _
    $eBackgroundColor, _
    $eBackgroundText, _
    $eBlue, _
    $eBorder, _
    $eBorderBottom, _
    $eBorderColor, _
    $eBorderLeft, _
    $eBorderRight, _
    $eBorderSize, _
    $eBorderTop, _
    $eBugReport, _
    $eBuild, _
    $eChangelog, _
    $eCheckbox, _
    $eCheckboxText, _
    $eConfig, _
    $eCss, _
    $eDocs, _
    $eDocsCodeOfConduct, _
    $eDocsContributing, _
    $eDocsPullRequestTemplate, _
    $eFeatureRequest, _
    $eFileActionHandler, _
    $eFileBugReport, _
    $eFileChangelog, _
    $eFileCodeOfConduct, _
    $eFileContributing, _
    $eFileFeatureRequest, _
    $eFileGitIgnore, _
    $eFileLicense, _
    $eFileProject, _
    $eFilePullRequestTemplate, _
    $eFileReadme, _
    $eFolder, _
    $eFont, _
    $eFontAttribute, _
    $eFontColor, _
    $eFontName, _
    $eFonts, _
    $eFontSize, _
    $eFontWeight, _
    $eGitIgnore, _
    $eHandle, _
    $eHeight, _
    $eIcons, _
    $eImages, _
    $eInput, _
    $eInputColor, _
    $eInputHeight, _
    $eInputText, _
    $eInputWidth, _
    $eInputXPosition, _
    $eInputYPosition, _
    $eIssueTemplate, _
    $eJs, _
    $eLabel, _
    $eLabelBackground, _
    $eLabelFontSize, _
    $eLabelHeight, _
    $eLabelText, _
    $eLabelWidth, _
    $eLabelXPosition, _
    $eLabelYPosition, _
    $eLicense, _
    $eMedia, _
    $eReadme, _
    $eRed, _
    $eRoot, _
    $eScreenshots, _
    $eSrc, _
    $eSrcActionHandler, _
    $eSrcHelper, _
    $eSrcInitializer, _
    $eSrcProject, _
    $eUtilities, _
    $eWhite, _
    $eWidth, _
    $eXPosition, _
    $eYPosition, _
    $iMaxEnumIndex
